name: hotelyn
repository: https://github.com/enzoftware/hotelyn

packages:
  - packages/hotelyn_components
  - packages/hotelyn_models
  - .
scripts:
  test:select:
    run: melos exec -- flutter test
    packageFilters:
      dirExists: test
    description: Run `flutter test` for selected packages.

  test:
    run: melos run test:select --no-select
    description: Run all Flutter tests in this project.

  coverage:
    run: |
      melos exec -- flutter test --coverage &&
      melos exec -- genhtml coverage/lcov.info --output-directory=coverage/
    packageFilters:
      dirExists: test
    description: Generate coverage for the selected package.

  update-goldens:
    run: melos exec -- flutter test --update-goldens
    packageFilters:
      dirExists: test
    description: Re-generate all golden test files