name: hotelyn_workspace
description: "Hotelyn Dart workspaces monorepo root."

environment:
  sdk: ">=3.5.0 <4.0.0"

workspace:
  - apps/hotelyn_app
  - packages/hotelyn_domain
  - packages/hotelyn_gql
  - packages/hotelyn_ui
  - server/hotelyn_server

dev_dependencies:
  melos: ^7.3.0
  very_good_analysis: ^10.0.0
