name: hotelyn_server
description: "Dart Frog GraphQL server for Hotelyn (talks to Supabase)."

version: 0.1.0+1

resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dev_dependencies:
  test: ^1.26.2
  very_good_analysis: ^10.3.0
