name: hotelyn_mocks
description: Mocks for the project, only for testing purposes
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  hotelyn_models:
    path: ../hotelyn_models

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
