name: hotelyn_ui
description: "Shared widget library and design system for Hotelyn."

version: 0.1.0+1

resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
