name: hotelyn_models

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/hotelyn_models/**"
      - ".github/workflows/hotelyn_models.yaml"
    branches:
      - master

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      working_directory: packages/hotelyn_models
